export const baseTheme = {
  "font-sans":
    '"Inter", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  "font-mono":
    "\"Geist Mono\", 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '\"Liberation Mono\"', '\"Courier New\"', 'monospace'",
  "font-sans--font-feature-settings": '"cv02", "cv03", "cv04", "cv11"',
  "font-mono--font-feature-settings": '"ss02", "zero"',
  "color-border": "var(--border)",
  "color-input": "var(--input)",
  "color-ring": "var(--ring)",
  "color-background": "var(--background)",
  "color-foreground": "var(--foreground)",
  "color-card": "var(--card)",
  "color-card-foreground": "var(--card-foreground)",
  "color-primary": "var(--primary)",
  "color-primary-foreground": "var(--primary-foreground)",
  "color-primary-subtle": "var(--primary-subtle)",
  "color-primary-subtle-foreground": "var(--primary-subtle-foreground)",
  "color-secondary": "var(--secondary)",
  "color-secondary-foreground": "var(--secondary-foreground)",
  "color-accent": "var(--accent)",
  "color-accent-foreground": "var(--accent-foreground)",
  "color-success": "var(--success)",
  "color-success-foreground": "var(--success-foreground)",
  "color-success-subtle": "var(--success-subtle)",
  "color-success-subtle-foreground": "var(--success-subtle-foreground)",
  "color-danger": "var(--danger)",
  "color-danger-foreground": "var(--danger-foreground)",
  "color-danger-subtle": "var(--danger-subtle)",
  "color-danger-subtle-foreground": "var(--danger-subtle-foreground)",
  "color-warning": "var(--warning)",
  "color-warning-foreground": "var(--warning-foreground)",
  "color-warning-subtle": "var(--warning-subtle)",
  "color-warning-subtle-foreground": "var(--warning-subtle-foreground)",
  "color-info-subtle": "var(--info-subtle)",
  "color-info-subtle-foreground": "var(--info-subtle-foreground)",
  "color-muted": "var(--muted)",
  "color-muted-foreground": "var(--muted-foreground)",
  "color-overlay": "var(--overlay)",
  "color-overlay-foreground": "var(--overlay-foreground)",
  "color-navbar": "var(--navbar)",
  "color-navbar-foreground": "var(--navbar-foreground)",
  "color-sidebar": "var(--sidebar)",
  "color-sidebar-foreground": "var(--sidebar-foreground)",
  "color-sidebar-primary": "var(--sidebar-primary)",
  "color-sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
  "color-sidebar-accent": "var(--sidebar-accent)",
  "color-sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
  "color-sidebar-border": "var(--sidebar-border)",
  "color-sidebar-ring": "var(--sidebar-ring)",
  "color-chart-1": "var(--chart-1)",
  "color-chart-2": "var(--chart-2)",
  "color-chart-3": "var(--chart-3)",
  "color-chart-4": "var(--chart-4)",
  "color-chart-5": "var(--chart-5)",
  "radius-sm": "calc(var(--radius) * 0.6)",
  "radius-md": "calc(var(--radius) * 0.8)",
  "radius-lg": "var(--radius)",
  "radius-xl": "calc(var(--radius) * 1.4)",
  "radius-2xl": "calc(var(--radius) * 1.8)",
  "radius-3xl": "calc(var(--radius) * 2.2)",
  "radius-4xl": "calc(var(--radius) * 2.6)",
}
