// Reorder the slug names in each subsection to customize the docs sidebar.
// Items omitted here appear at the end in their original order.
export const componentOrder: Record<string, readonly string[]> = {
  Buttons: ["button", "button-group", "toggle", "toggle-group", "file-trigger"],
  Collections: [
    "menu",
    "table",
    "grid-list",
    "list-box",
    "tag-group",
    "tree",
    "choice-box",
    "dropdown",
    "autocomplete",
    "virtualizer",
  ],
  Colors: [
    "color-field",
    "color-picker",
    "color-area",
    "color-slider",
    "color-swatch",
    "color-swatch-picker",
    "color-thumb",
    "color-wheel",
  ],
  Controls: [
    "toolbar",
    "switch",
    "command-menu",
    "context-menu",
    "keyboard",
    "slider",
    "scroll-area",
  ],
  "Date And Time": [
    "calendar",
    "range-calendar",
    "date-field",
    "date-picker",
    "date-range-picker",
    "time-field",
  ],
  "Drag And Drop": ["drop-zone"],
  Forms: [
    "checkbox",
    "checkbox-group",
    "field",
    "input",
    "input-otp",
    "number-field",
    "search-field",
    "tag-field",
    "text-field",
    "textarea",
    "radio-group",
  ],
  Layouts: ["container", "navbar", "sidebar"],
  Media: ["avatar", "carousel"],
  Navigation: [
    "disclosure",
    "disclosure-group",
    "breadcrumbs",
    "tabs",
    "link",
    "pagination",
    "snippet",
  ],
  Overlays: ["modal", "sheet", "drawer", "popover", "preview", "tooltip", "dialog"],
  Pickers: ["select", "multiple-select", "native-select", "combo-box"],
  Statuses: [
    "badge",
    "loader",
    "meter",
    "note",
    "progress-bar",
    "progress-circle",
    "skeleton",
    "toast",
  ],
  Surfaces: ["heading", "card", "description-list", "separator", "show-more", "text"],
  Visualizations: [
    "chart",
    "area-chart",
    "line-chart",
    "bar-chart",
    "pie-chart",
    "radar-chart",
    "radial-bar-chart",
    "leaderboard",
    "bar-list",
    "tracker",
  ],
}
