"use client"

import { useCallback, useRef } from "react"
import { cn } from "cn"
import { CopyButton } from "@/components/docs/copy-button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { useClipboard } from "@/hooks/use-clipboard"

export interface PreProps extends React.HTMLAttributes<HTMLElement> {
  ref?: React.Ref<HTMLElement>
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: React.ReactNode

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
}

export const Pre = ({ className, ref, ...props }: React.ComponentProps<"pre">) => {
  return (
    <pre
      ref={ref}
      className={cn("w-full p-4 text-sm/8 focus-visible:outline-hidden", className)}
      {...props}
    >
      {props.children}
    </pre>
  )
}

export const PlainCode = ({
  className,
  title,
  allowCopy = true,
  icon,
  ref,
  ...props
}: PreProps) => {
  const areaRef = useRef<HTMLDivElement>(null)
  const { copy, copied } = useClipboard()
  const onCopy = useCallback(async () => {
    const pre = areaRef.current?.getElementsByTagName("pre").item(0)

    if (!pre) return

    const clone = pre.cloneNode(true) as HTMLElement
    for (const node of clone.querySelectorAll(".nd-copy-ignore")) {
      node.remove()
    }
    await copy(clone.textContent ?? "")
  }, [copy])
  return (
    <figure
      ref={ref}
      {...props}
      className={cn(
        "not-typeset group relative my-6 max-w-4xl overflow-hidden rounded-lg border bg-secondary/50 text-sm/6",
        className
      )}
    >
      {title ? (
        <div className="flex w-full flex-row items-center gap-2 border-b px-4 py-1.5">
          {icon ? (
            <div
              className="text-muted-fg [&_svg]:size-3.5"
              dangerouslySetInnerHTML={
                typeof icon === "string"
                  ? {
                      __html: icon,
                    }
                  : undefined
              }
            >
              {typeof icon !== "string" ? icon : null}
            </div>
          ) : null}
          <figcaption className="flex-1 truncate text-muted-fg">{title}</figcaption>
          {allowCopy ? (
            <CopyButton
              className="absolute top-1 right-1 z-2 grid size-10 place-content-center"
              onPress={onCopy}
              isCopied={copied}
            />
          ) : null}
        </div>
      ) : (
        allowCopy && (
          <CopyButton
            className="absolute top-1 right-1 z-2 grid size-10 place-content-center"
            onPress={onCopy}
            isCopied={copied}
          />
        )
      )}

      <ScrollArea ref={areaRef} orientation="both" className="w-full *:max-h-150" scrollFade>
        {props.children}
      </ScrollArea>
    </figure>
  )
}
